#!/usr/bin/env python3
"""Translation catalogue for the site.

The pages carry their text as adjacent `<tag lang="en">…</tag><tag lang="uk">…</tag>`
pairs. That works for two languages and falls apart at thirty-two, so the
strings are pulled out here into one table that can be handed to a translator
and read back in.

Strings are keyed by their English text, the same way the desktop app's tr()
works, so a key is readable on its own and duplicates collapse to one row.

    python3 tools/site/i18n.py extract    # pages  -> strings.csv
    python3 tools/site/i18n.py migrate    # one-off: markup -> lookups
    python3 tools/site/i18n.py import F   # a translator's table -> strings.csv
    python3 tools/site/i18n.py apply      # strings.csv -> docs/_data/i18n/
    python3 tools/site/i18n.py check      # what is still untranslated
"""
import argparse
import csv
import html
import re
import sys
import yaml
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"
OUT = Path(__file__).resolve().parent / "i18n"
TABLE = OUT / "strings.csv"
DATA = DOCS / "_data" / "i18n"

SOURCE = "en"

# Where the pages live. _site and _preview are build output.
PAGES = sorted(
    p for p in list(DOCS.glob("*.html")) + list(DOCS.glob("_includes/*.html"))
    + list(DOCS.glob("_layouts/*.html"))
    if "_site" not in p.parts and "_preview" not in p.parts)

# hero-stage*.html is generated by build_hero.py; its strings really live in
# that script's SCREENS/NAMES/MORE tables, so the `where` column points there
# and anything applied to the HTML would be overwritten on the next build.
GENERATED = {"hero-stage.html", "hero-stage-phone.html", "hero-stage-reader.html"}
GENERATED_HOME = "tools/site/build_hero.py"


def languages():
    """Interface languages, taken from the app's own locales."""
    codes = sorted(p.stem.replace("_", "-") for p in (ROOT / "locales").glob("*.py")
                   if p.stem != "__init__")
    return codes


def _close(text, start, tag):
    """End of the element opening at `start`, honouring nesting."""
    depth, i = 0, start
    open_re = re.compile(rf"<{tag}\b", re.I)
    close_re = re.compile(rf"</{tag}\s*>", re.I)
    while i < len(text):
        o = open_re.search(text, i)
        c = close_re.search(text, i)
        if not c:
            return None, None
        if o and o.start() < c.start():
            depth += 1
            i = o.end()
            continue
        if depth == 0:
            return c.start(), c.end()
        depth -= 1
        i = c.end()
    return None, None


PAIR = re.compile(r'<(?P<tag>[a-z0-9]+)\b[^>]*\blang="(?P<lang>en|uk)"[^>]*>', re.I)

# lang on <html> is the document's own language, not a string to translate.
CONTENT_TAGS = {"span", "a", "p", "li", "h1", "h2", "h3", "h4",
                "strong", "em", "small", "button", "summary", "div", "td", "th"}


def elements(path, text=None):
    """Every lang-tagged element in document order, with its position."""
    text = path.read_text(encoding="utf-8") if text is None else text
    out, pos = [], 0
    while True:
        m = PAIR.search(text, pos)
        if not m:
            return out
        tag = m.group("tag").lower()
        if tag not in CONTENT_TAGS:
            pos = m.end()
            continue
        end, after = _close(text, m.end(), tag)
        if end is None:
            sys.exit(f'{path.name}: unclosed <{tag} lang="{m.group("lang")}">')
        out.append({"tag": tag, "lang": m.group("lang"),
                    "body": text[m.end():end].strip(),
                    "open": m.group(0), "start": m.start(), "end": after})
        pos = after


def pairs(path, text=None):
    """English element paired with its Ukrainian twin.

    Paired by order, not by adjacency: most of the site writes the two
    languages side by side, but the KOReader install steps list all the English
    items first and then all the Ukrainian ones.
    """
    items = elements(path, text)
    en = [e for e in items if e["lang"] == "en"]
    uk = [e for e in items if e["lang"] == "uk"]
    if len(en) != len(uk):
        sys.exit(f"{path.name}: {len(en)} en vs {len(uk)} uk elements")
    for a, b in zip(en, uk, strict=True):
        if a["tag"] != b["tag"]:
            sys.exit(f"{path.name}: <{a['tag']}> paired with <{b['tag']}> "
                     f"at {a['body'][:40]!r}")
    return list(zip(en, uk, strict=True))


def scan(path):
    for a, b in pairs(path):
        yield a["body"], b["body"]


CALL = re.compile(r"\{%\s*include t\.html s='([^']*)'\s*%\}")

# i18n-js.html hands strings to the scripts as JSON, so it reads the catalogue
# directly instead of going through t.html.
DIRECT = re.compile(r"\{\{\s*c\['([^']*)'\]")


def sources():
    return sorted(set(PAGES) | set(DOCS.glob("_includes/pages/*.html")))


def collect():
    """Every string the pages ask for, in the order they are first met."""
    where = {}

    def note(s, rel):
        where.setdefault(s, [])
        if rel not in where[s]:
            where[s].append(rel)

    for path in sources():
        rel = (GENERATED_HOME if path.name in GENERATED
               else str(path.relative_to(ROOT)))
        text = path.read_text(encoding="utf-8")
        for s in CALL.findall(text) + DIRECT.findall(text):
            note(s, rel)

    # The <title> and meta description sit in front matter, not in the body.
    for filename in TRANSLATED_PAGES:
        front, _ = _split_front((DOCS / filename).read_text(encoding="utf-8"))
        for key in ("title", "description"):
            if front.get(key):
                note(front[key], f"docs/{filename}")
    return where


def read_table():
    if not TABLE.exists():
        sys.exit(f"no {TABLE.relative_to(ROOT)} — run `extract` first")
    with TABLE.open(encoding="utf-8-sig", newline="") as fh:
        return list(csv.DictReader(fh))


def cmd_extract(args):
    where = collect()
    langs = languages()

    # Keep anything already translated, so re-running never loses work.
    have = {r["text"]: r for r in read_table()} if TABLE.exists() else {}

    OUT.mkdir(parents=True, exist_ok=True)
    cols = ["text", "where"] + langs
    with TABLE.open("w", encoding="utf-8-sig", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=cols)
        w.writeheader()
        for text, files in where.items():
            row = dict(have.get(text, {}))
            row["text"] = text
            row["where"] = " ".join(files)
            w.writerow({c: row.get(c, "") or "" for c in cols})

    gone = [t for t in have if t not in where]
    print(f"{len(where)} strings from {len(sources())} files "
          f"-> {TABLE.relative_to(ROOT)}")
    print(f"{len(langs)} languages")
    if gone:
        print(f"dropped {len(gone)} no longer used: "
              + ", ".join(repr(t[:34]) for t in gone[:4]))


# Header cells name the language in prose and the code in brackets:
# "Swedish (sv)", "Chinese (Simplified) [zh-CN]". The first column is English.
HEADER_CODE = re.compile(r"[(\[]\s*([A-Za-z]{2,3}(?:-[A-Za-z]{2,4})?)\s*[)\]]")

# Codes a translator may hand back that are one of ours under another name.
ALIASES = {"zh-CN": "zh", "zh-Hans": "zh", "zh-TW": "zh", "pt-PT": "pt",
           "nb-NO": "nb", "no": "nb", "he": "iw"}


def _match_key(s):
    """A loose form of a string, for pairing tables back to the catalogue.

    Round trips through a spreadsheet or a translation tool come back with
    &amp; decoded and the odd tag dropped, so the English column rarely
    matches byte for byte even when it is plainly the same string.
    """
    s = re.sub(r"<[^>]+>", "", html.unescape(s))
    return re.sub(r"\s+", " ", s).strip().lower()


def _columns(header, langs):
    """Language code per column index, skipping English and anything unknown."""
    out, unknown = {}, []
    for i, cell in enumerate(header[1:], 1):
        m = HEADER_CODE.search(cell)
        code = ALIASES.get(m.group(1), m.group(1)) if m else None
        if code in langs:
            out[i] = code
        else:
            unknown.append(cell.strip())
    return out, unknown


def cmd_import(args):
    rows = read_table()
    langs = [c for c in rows[0] if c not in ("text", "where")]
    index = {_match_key(r["text"]): r for r in rows}

    for path in args.files:
        path = Path(path)
        with path.open(encoding="utf-8-sig", newline="") as fh:
            table = [r for r in csv.reader(fh) if r and r[0].strip()]
        if not table:
            print(f"{path.name}: empty")
            continue
        cols, unknown = _columns(table[0], langs)
        if unknown:
            print(f"{path.name}: skipping column(s) {', '.join(unknown)}")
        filled = {c: 0 for c in cols.values()}
        missed = 0
        for row in table[1:]:
            target = index.get(_match_key(row[0]))
            if target is None:
                missed += 1
                continue
            for i, code in cols.items():
                value = row[i].strip() if i < len(row) else ""
                if value and (args.overwrite or not target.get(code, "").strip()):
                    target[code] = value
                    filled[code] += 1
        counts = " ".join(f"{c}({n})" for c, n in filled.items())
        tail = f", {missed} rows unmatched" if missed else ""
        print(f"{path.name}: {counts}{tail}")

    cols = ["text", "where"] + langs
    with TABLE.open("w", encoding="utf-8-sig", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=cols)
        w.writeheader()
        for row in rows:
            w.writerow({c: row.get(c, "") or "" for c in cols})
    print(f"-> {TABLE.relative_to(ROOT)}")


def cmd_apply(args):
    rows = read_table()
    langs = [c for c in rows[0] if c not in ("text", "where")] if rows else []
    DATA.mkdir(parents=True, exist_ok=True)
    written = []
    for lang in langs:
        done = [(r["text"], r[lang]) for r in rows if r.get(lang, "").strip()]
        if not done:
            continue
        head = "# Generated by tools/site/i18n.py — edit strings.csv instead.\n\n"
        # safe_dump, not hand-rolled quoting: a few strings run over several
        # lines (the KOReader install steps carry a nested list).
        text = yaml.safe_dump(dict(done), allow_unicode=True, sort_keys=False,
                              default_flow_style=False, width=10 ** 6)
        (DATA / f"{lang}.yml").write_text(head + text, encoding="utf-8")
        written.append(f"{lang}({len(done)})")
    print(f"wrote {len(written)} files into {DATA.relative_to(ROOT)}")
    print("  " + " ".join(written))


def _yaml(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _call(s):
    return "{%% include t.html s='%s' %%}" % s


def _rewritten(el):
    """The English element, with its twin folded into a lookup.

    A <span> that carried nothing but lang= disappears entirely — it only ever
    existed to hold the language — while anything with real attributes keeps
    its tag and loses just the lang.
    """
    attrs = re.sub(r'\s*\blang="en"', "", el["open"][1 + len(el["tag"]):-1]).rstrip()
    if el["tag"] == "span" and not attrs:
        return _call(el["body"])
    return f'<{el["tag"]}{attrs}>{_call(el["body"])}</{el["tag"]}>'


def cmd_migrate(args):
    """Turn the two-language markup into single-language markup plus lookups."""
    for path in PAGES:
        if path.name in GENERATED:
            continue
        text = path.read_text(encoding="utf-8")
        found = pairs(path, text)
        if not found:
            continue
        edits = []
        for en, uk in found:
            edits.append((uk["start"], uk["end"], ""))
            edits.append((en["start"], en["end"], _rewritten(en)))
        for start, end, repl in sorted(edits, reverse=True):
            text = text[:start] + repl + text[end:]
        # Deleting the Ukrainian twin can leave the line it sat on behind.
        text = re.sub(r"\n[ \t]*\n[ \t]*\n", "\n\n", text)
        path.write_text(text, encoding="utf-8")
        print(f"  {path.relative_to(ROOT)}  {len(found)} strings")


# The marketing pages that get a copy per language. 404 stays English-only:
# GitHub Pages serves one /404.html for the whole site.
TRANSLATED_PAGES = {"index.html": "/", "download.html": "/download/",
                    "mobile.html": "/mobile/", "koreader.html": "/koreader/"}
BODIES = DOCS / "_includes" / "pages"
SITE_URL = "https://lingueez.app"

# What each language calls itself, for the picker in the nav.
NAMES = {
    "en": "English", "bg": "Български", "cs": "Čeština", "da": "Dansk",
    "de": "Deutsch", "el": "Ελληνικά", "es": "Español", "fi": "Suomi",
    "fr": "Français", "hi": "हिन्दी", "hr": "Hrvatski", "hu": "Magyar",
    "id": "Indonesia", "it": "Italiano", "ja": "日本語", "ko": "한국어",
    "ms": "Melayu", "nb": "Norsk", "nl": "Nederlands", "pl": "Polski",
    "pt": "Português", "pt-BR": "Português (BR)", "ro": "Română",
    "ru": "Русский", "sk": "Slovenčina", "sr": "Српски", "sv": "Svenska",
    "th": "ไทย", "tr": "Türkçe", "uk": "Українська", "vi": "Tiếng Việt",
    "zh": "中文",
}


# A language joins the site once its catalogue is essentially complete. Below
# this it would publish a page that is mostly English at a translated URL —
# worse than not offering the language at all, and a lie to hreflang.
MIN_COVERAGE = 0.9


def shipped():
    """Languages complete enough to publish."""
    rows = read_table()
    langs = [c for c in rows[0] if c not in ("text", "where")]
    return [c for c in langs
            if sum(1 for r in rows if r.get(c, "").strip()) >= len(rows) * MIN_COVERAGE]


def _split_front(text):
    if not text.startswith("---"):
        sys.exit("page has no front matter")
    _, front, body = text.split("---", 2)
    return yaml.safe_load(front), body.lstrip("\n")


def _stub(front, lang, ref, base):
    prefix = "" if lang == SOURCE else f"/{lang}"
    page = dict(front)
    page["lang"] = lang
    page["ref"] = ref
    page["base"] = base
    page["permalink"] = f"{prefix}{base}"
    page["canonical"] = f"{SITE_URL}{prefix}{base}"
    ordered = {k: page[k] for k in
               ["layout", "lang", "ref", "base", "permalink", "title", "description",
                "image", "canonical", "nav_active", "robots", "styles", "scripts"]
               if k in page}
    front_yaml = yaml.safe_dump(ordered, allow_unicode=True, sort_keys=False,
                                default_flow_style=False, width=10 ** 6)
    return f"---\n{front_yaml}---\n\n{{% include pages/{ref}.html %}}\n"


def cmd_pages(args):
    """Split each page into a shared body plus one thin file per language."""
    langs = [SOURCE] + shipped()
    BODIES.mkdir(parents=True, exist_ok=True)
    (DOCS / "_data").mkdir(exist_ok=True)
    # Each entry carries its own URL prefix so templates never have to branch
    # on "is this English"; English's prefix is simply empty.
    table = [{"code": c, "prefix": "" if c == SOURCE else f"/{c}",
              "name": NAMES.get(c, c)} for c in langs]
    (DOCS / "_data" / "languages.yml").write_text(
        "# Generated by tools/site/i18n.py\n"
        + yaml.safe_dump(table, allow_unicode=True, sort_keys=False),
        encoding="utf-8")

    for filename, base in TRANSLATED_PAGES.items():
        ref = "home" if filename == "index.html" else Path(filename).stem
        src = DOCS / filename
        front, body = _split_front(src.read_text(encoding="utf-8"))
        # First run holds the real body; later runs are already stubs.
        if "{% include pages/" not in body:
            (BODIES / f"{ref}.html").write_text(body, encoding="utf-8")
        for lang in langs:
            out = src if lang == SOURCE else DOCS / lang / filename
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(_stub(front, lang, ref, base), encoding="utf-8")
        print(f"  {ref:9s} {len(langs)} pages")

    # A language that has fallen below the bar leaves its pages behind, and a
    # stale stub still answers on its URL. Clear them out.
    dropped = []
    for code in languages():
        if code in langs:
            continue
        folder = DOCS / code
        for filename in TRANSLATED_PAGES:
            (folder / filename).unlink(missing_ok=True)
        if folder.is_dir() and not any(folder.iterdir()):
            folder.rmdir()
            dropped.append(code)
    if dropped:
        print(f"  removed {len(dropped)} untranslated: " + " ".join(dropped))


def cmd_check(args):
    rows = read_table()
    langs = [c for c in rows[0] if c not in ("text", "where")]
    total = len(rows)
    live = set(shipped())
    print(f"{total} strings; {len(live)} languages live "
          f"(the site carries a language at {MIN_COVERAGE:.0%})")
    for lang in langs:
        n = sum(1 for r in rows if r.get(lang, "").strip())
        bar = "#" * round(n / total * 24)
        flag = "" if n == total else f"  {total - n} missing"
        print(f"  {'*' if lang in live else ' '} {lang:6s} {n:4d}/{total} {bar:<24}{flag}")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("extract").set_defaults(fn=cmd_extract)
    sub.add_parser("apply").set_defaults(fn=cmd_apply)
    sub.add_parser("migrate").set_defaults(fn=cmd_migrate)
    imp = sub.add_parser("import")
    imp.add_argument("files", nargs="+", help="tables with English in column 1")
    imp.add_argument("--overwrite", action="store_true",
                     help="replace translations already in the table")
    imp.set_defaults(fn=cmd_import)
    sub.add_parser("pages").set_defaults(fn=cmd_pages)
    sub.add_parser("check").set_defaults(fn=cmd_check)
    args = ap.parse_args()
    args.fn(args)


if __name__ == "__main__":
    main()
