# Lingueez — a desktop app for studying vocabulary across languages.
# Copyright (C) 2024-2026 Yurii Lysak
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Regenerate LANGUAGES.md from the code that actually defines the support.

The table is derived from locales/*.py and app.core.languages, never hand-
edited — a typed-out copy goes stale the first time a locale is added.
tests/test_languages_doc.py fails when the checked-in file drifts from what
render() produces here.

Run:  python tools/gen_languages_md.py        # rewrites LANGUAGES.md
"""

import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)

from app.core.languages import (  # noqa: E402
    DEEPL_CODES, SPEECH_CODES, TRANSLATION_CODES,
)

OUTPUT = os.path.join(REPO, "LANGUAGES.md")

# Locale codes whose language name can't be recovered by reversing
# TRANSLATION_CODES: regional variants, and codes the two lists spell
# differently (the app speaks of Mandarin, the locale file is plain `zh`).
LOCALE_NAME_OVERRIDES = {
    "nb": "Norwegian",       # TRANSLATION_CODES uses the macrolanguage code "no"
    "pt_BR": "Portuguese",   # ships alongside European Portuguese
    "zh": "Mandarin",        # TRANSLATION_CODES splits zh into Mandarin/Cantonese
}


def interface_languages():
    """English language name -> the locale codes shipping a UI translation."""
    by_code = {code: name for name, code in TRANSLATION_CODES.items()}
    names = {}
    codes = sorted(f[:-3] for f in os.listdir(os.path.join(REPO, "locales"))
                   if f.endswith(".py") and not f.startswith("__"))
    for code in codes:
        name = LOCALE_NAME_OVERRIDES.get(code) or by_code.get(code)
        if not name:
            raise SystemExit(
                f"locales/{code}.py: cannot map to an English language name. "
                f"Add it to LOCALE_NAME_OVERRIDES in {__file__}.")
        names.setdefault(name, []).append(code)
    return names


def render():
    """The full contents of LANGUAGES.md."""
    ui = interface_languages()
    ui_count = sum(len(v) for v in ui.values()) + 1  # + English, which has no module
    rows = []
    for name in sorted(TRANSLATION_CODES):
        rows.append((
            name,
            "✓" if name in ui or name == "English" else "—",
            "✓",  # every row is a language the app can translate
            "✓" if name in SPEECH_CODES else "—",
        ))
    width = max(len(name) for name, *_ in rows)

    out = [
        "# Supported languages",
        "",
        "Generated by `tools/gen_languages_md.py` — do not edit by hand.",
        "",
        f"- **Interface** — {ui_count} languages the app itself is translated into.",
        f"- **Translate** — {len(TRANSLATION_CODES)} languages you can add words and texts in.",
        f"- **Speech** — {len(SPEECH_CODES)} of those have a text-to-speech voice.",
        "",
        "Translation and speech come from different services with different coverage, "
        f"so {len(TRANSLATION_CODES) - len(SPEECH_CODES)} languages can be translated but not "
        "spoken. The app greys out the pronounce button for those rather than failing "
        "on a click.",
        "",
        f"| {'Language'.ljust(width)} | Interface | Translate | Speech |",
        f"| {'-' * width} | :-------: | :-------: | :----: |",
    ]
    for name, has_ui, has_tr, has_tts in rows:
        out.append(f"| {name.ljust(width)} |     {has_ui}     |     {has_tr}     "
                   f"|   {has_tts}    |")
    out += [
        "",
        "Portuguese ships two interface translations (European and Brazilian); "
        "Chinese is listed as Mandarin and Cantonese, which the speech and "
        "translation services treat as separate languages.",
        "",
        f"Translation uses Google Translate by default. With a DeepL API key "
        f"configured, {len(DEEPL_CODES)} of these languages go through DeepL "
        "automatically and the rest continue to use Google — no setup needed "
        "either way.",
        "",
    ]
    return "\n".join(out)


if __name__ == "__main__":
    # Render before opening: "w" truncates on open, so building the text first
    # means a failure here leaves the existing LANGUAGES.md intact.
    text = render()
    with open(OUTPUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"wrote {OUTPUT}")
