# Lingueez — a desktop app for studying vocabulary across languages.
# Copyright (C) 2024-2026 Yurii Lysak
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Additional terms under AGPL-3.0 section 7 apply to this program; see the
# NOTICE file distributed with this source for details.
#
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Postgres DDL for the user's own Supabase project (bring-your-own backend).

Only four of the local SQLite tables are mirrored to the cloud — words, texts,
tags, word_tags — with lowercase/snake_case columns (see
``SupabaseClient._map_to_supabase_format``) plus a ``deleted_at`` column the
local tables lack, used for soft-delete sync. Kept as a Python constant rather
than a bundled ``.sql`` resource so it ships intact in the frozen build.
"""

# Run this once in the Supabase SQL editor. Surfaced verbatim to the user via
# Settings → APIs → Sync ("Copy schema SQL"). Keep it in sync with the cloud
# column names in supabase_client.py and the unique constraint upsert_word relies on.
SCHEMA_SQL = """\
-- Lingueez cloud sync schema.
-- Run this once in your Supabase project's SQL editor (paste, then Run).
-- Only these four tables are synced; everything else stays on your device.
--
-- Row-Level Security is intentionally left OFF: this is YOUR private project
-- and the app authenticates with your project's anon key. Keep the project
-- private and do not share its keys.

create table if not exists words (
    id          bigint primary key generated by default as identity,
    row_number  bigint,
    source      text,
    definition  text,
    definition2 text,
    status      text,
    language1   text,
    word1       text,
    language2   text,
    word2       text,
    created_at  timestamptz default now(),
    edited_at   timestamptz,
    deleted_at  timestamptz,
    favorite    boolean default false,
    constraint words_word1_word2_key unique (word1, word2)
);

create table if not exists texts (
    id          bigint primary key generated by default as identity,
    row_number  bigint,
    title       text,
    words       text,
    text        text,
    language    text,
    category    text,
    level       text,
    created_at  timestamptz default now(),
    edited_at   timestamptz,
    deleted_at  timestamptz
);

create table if not exists tags (
    tag_id   bigint primary key generated by default as identity,
    tag_name text unique not null
);

create table if not exists word_tags (
    word_id bigint not null references words(id) on delete cascade,
    tag_id  bigint not null references tags(tag_id) on delete cascade,
    primary key (word_id, tag_id)
);
"""
