# Lingueez — a desktop app for studying vocabulary across languages.
# Copyright (C) 2024-2026 Yurii Lysak
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Additional terms under AGPL-3.0 section 7 apply to this program; see the
# NOTICE file distributed with this source for details.
#
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Postgres DDL for a multi-user Supabase backend (hosted central database).

Only four of the local SQLite tables are mirrored to the cloud — words, texts,
tags, word_tags — with lowercase/snake_case columns (see
``SupabaseClient._map_to_supabase_format``) plus a ``deleted_at`` column the
local tables lack, used for soft-delete sync. Kept as a Python constant rather
than a bundled ``.sql`` resource so it ships intact in the frozen build.

Each row carries a ``user_id`` and Row-Level Security is ON, so every account
sees and touches only its own rows even though the app ships a public anon key —
RLS is what makes that public key safe. Uniqueness is per-user, so two accounts
may hold the same word pair / tag name. Registration is **open** (anyone can sign
up); abuse is held off by email verification + Supabase's built-in rate limits,
not by an allowlist.

Email verification is by **6-digit code**, not a confirmation link, because this
is a desktop app with no web page to land on. Two dashboard settings make that
work (operational, not in this SQL):
  • Authentication → Providers → Email → keep "Confirm email" ON, and configure a
    real SMTP provider (Authentication → Emails) so codes actually deliver.
  • Authentication → Emails → "Confirm signup" template: use the token, e.g.
    ``<p>Your Lingueez code is <b>{{ .Token }}</b></p>`` (the default template
    sends a {{ .ConfirmationURL }} link, which a desktop app can't catch).
"""

# Run this once in the Supabase SQL editor of a fresh, EU-region project (paste,
# then Run). Surfaced verbatim to the user via Settings → Sync ("Copy schema
# SQL"). Keep it in sync with the cloud column names in supabase_client.py and
# the per-user unique constraint upsert_word relies on. The script is idempotent
# (safe to re-run). A RESET appendix at the bottom covers upgrading a project that
# still has the older integer-id schema; a brand-new project ignores it.
SCHEMA_SQL = """\
-- =====================================================================
-- Lingueez cloud sync schema (multi-user, Row-Level Security ON).
-- Run once in a fresh EU-region Supabase project's SQL editor.
-- The desktop app syncs only the four dictionary tables (words/texts/tags/
-- word_tags); the learning/stats tables and device_auth below are for the
-- Lingueez web app and the KOReader plugin sharing this same backend.
-- Safe to re-run (idempotent).
-- =====================================================================

-- ---- Tables -----------------------------------------------------------
-- Primary keys are UUIDs generated by the desktop client (same value locally and
-- here), so sync is a plain upsert on `id`. The `default gen_random_uuid()` is
-- only a safety net for rows inserted without an explicit id.
create table if not exists words (
    id          uuid primary key default gen_random_uuid(),
    user_id     uuid not null default auth.uid() references auth.users(id) on delete cascade,
    row_number  bigint,
    source      text,
    definition  text,
    definition2 text,
    status      text,
    language1   text,
    word1       text,
    language2   text,
    word2       text,
    created_at  timestamptz default now(),
    edited_at   timestamptz,
    deleted_at  timestamptz,
    favorite    boolean default false,
    constraint words_user_word_key unique (user_id, word1, word2)
);

create table if not exists texts (
    id          uuid primary key default gen_random_uuid(),
    user_id     uuid not null default auth.uid() references auth.users(id) on delete cascade,
    row_number  bigint,
    title       text,
    words       text,
    text        text,
    language    text,
    category    text,
    level       text,
    created_at  timestamptz default now(),
    edited_at   timestamptz,
    deleted_at  timestamptz
);

create table if not exists tags (
    tag_id   uuid primary key default gen_random_uuid(),
    user_id  uuid not null default auth.uid() references auth.users(id) on delete cascade,
    tag_name text not null,
    constraint tags_user_name_key unique (user_id, tag_name)
);

create table if not exists word_tags (
    word_id uuid not null references words(id) on delete cascade,
    tag_id  uuid not null references tags(tag_id) on delete cascade,
    user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
    primary key (word_id, tag_id)
);

-- ---- Row-Level Security: each user sees only their own rows ------------
alter table words     enable row level security;
alter table texts     enable row level security;
alter table tags      enable row level security;
alter table word_tags enable row level security;

drop policy if exists own_rows on words;
create policy own_rows on words     for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists own_rows on texts;
create policy own_rows on texts     for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists own_rows on tags;
create policy own_rows on tags      for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists own_rows on word_tags;
create policy own_rows on word_tags for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---- Learning / stats tables (used by the Lingueez WEB app) -----------
-- The desktop app doesn't use these (it keeps learning data on-device); they
-- live here so the Lingueez web app, pointed at this project, can store
-- sessions, spaced-repetition progress, quiz results, AI tutor chats, per-word
-- AI context and settings. Same per-user model + RLS as the dictionary tables.
create table if not exists word_progress (
    user_id       uuid not null default auth.uid() references auth.users(id) on delete cascade,
    word_id       uuid not null references words(id) on delete cascade,
    last_reviewed timestamptz,
    next_review   timestamptz,
    difficulty    integer default 3,
    review_count  integer default 0,
    correct_count integer default 0,
    ease_factor   real    default 2.5,
    interval_days integer default 1,
    created_at    timestamptz default now(),
    updated_at    timestamptz default now(),
    primary key (user_id, word_id)
);
create index if not exists idx_word_progress_user_next_review on word_progress(user_id, next_review);

create table if not exists learning_sessions (
    id            uuid primary key default gen_random_uuid(),
    user_id       uuid not null default auth.uid() references auth.users(id) on delete cascade,
    session_type  text,
    word_ids      text,
    started_at    timestamptz default now(),
    completed_at  timestamptz,
    words_studied integer default 0,
    words_correct integer default 0
);
create index if not exists idx_learning_sessions_user_started on learning_sessions(user_id, started_at);

create table if not exists quiz_results (
    id             uuid primary key default gen_random_uuid(),
    user_id        uuid not null default auth.uid() references auth.users(id) on delete cascade,
    session_id     uuid references learning_sessions(id) on delete cascade,
    word_id        uuid references words(id) on delete cascade,
    question       text,
    user_answer    integer,
    correct_answer integer,
    is_correct     boolean,
    answered_at    timestamptz default now()
);
create index if not exists idx_quiz_results_session_id on quiz_results(session_id);
create index if not exists idx_quiz_results_user_word on quiz_results(user_id, word_id);

create table if not exists ai_conversations (
    id         uuid primary key default gen_random_uuid(),
    user_id    uuid not null default auth.uid() references auth.users(id) on delete cascade,
    messages   text,
    title      text,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);
create index if not exists idx_ai_conversations_user on ai_conversations(user_id);

create table if not exists word_context (
    user_id           uuid not null default auth.uid() references auth.users(id) on delete cascade,
    word_id           uuid not null references words(id) on delete cascade,
    example_sentences jsonb default '[]',
    collocations      jsonb default '[]',
    usage_patterns    jsonb default '{}',
    synonyms          jsonb default '[]',
    antonyms          jsonb default '[]',
    difficulty_level  text default 'intermediate',
    frequency_rank    integer,
    created_at        timestamptz default now(),
    updated_at        timestamptz default now(),
    primary key (user_id, word_id)
);
create index if not exists idx_word_context_updated on word_context(updated_at);

create table if not exists user_settings (
    user_id                uuid primary key default auth.uid() references auth.users(id) on delete cascade,
    activity_defaults      jsonb default '{}',
    flashcard_show_context boolean default false,
    updated_at             timestamptz default now()
);

alter table word_progress     enable row level security;
alter table learning_sessions enable row level security;
alter table quiz_results      enable row level security;
alter table ai_conversations  enable row level security;
alter table word_context      enable row level security;
alter table user_settings     enable row level security;

drop policy if exists own_rows on word_progress;
create policy own_rows on word_progress     for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists own_rows on learning_sessions;
create policy own_rows on learning_sessions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists own_rows on quiz_results;
create policy own_rows on quiz_results      for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists own_rows on ai_conversations;
create policy own_rows on ai_conversations  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists own_rows on word_context;
create policy own_rows on word_context      for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists own_rows on user_settings;
create policy own_rows on user_settings     for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---- Open registration --------------------------------------------------
-- Anyone may sign up; there is no invite allowlist. New accounts are verified by
-- a 6-digit email code (configure SMTP + the "Confirm signup" email template to
-- use {{ .Token }} — see the module docstring). If this project was created with
-- the old invite-only trigger, the migration appendix below removes it.

-- ---- GDPR: let a signed-in user delete their own account + all data ----
-- A client with the anon key cannot delete an auth.users row directly, so this
-- SECURITY DEFINER function does it on the user's behalf. The on-delete-cascade
-- foreign keys above then wipe every one of their rows atomically. No
-- service-role key is ever needed (or shipped) for this.
create or replace function public.delete_account()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from auth.users where id = auth.uid();
end;
$$;

revoke all on function public.delete_account() from public, anon;
grant execute on function public.delete_account() to authenticated;

-- ---- Device-link rendezvous for the KOReader plugin's QR Google sign-in --
-- The reader shows a QR of the Google authorize URL; the phone completes OAuth
-- and a small static page drops the returned auth code here, keyed by a random
-- device_id; the reader polls for it and finishes the PKCE exchange itself. The
-- stored code is PKCE-bound (useless without the code_verifier that never leaves
-- the reader), so anon read access is safe; device_id is the lookup secret.
create table if not exists device_auth (
  device_id  text primary key,
  code       text not null,
  created_at timestamptz not null default now()
);
alter table device_auth enable row level security;

-- Phone (anon) writes the code; reader (anon) reads it then deletes it.
drop policy if exists device_auth_anon_insert on device_auth;
create policy device_auth_anon_insert on device_auth for insert to anon with check (true);
drop policy if exists device_auth_anon_select on device_auth;
create policy device_auth_anon_select on device_auth for select to anon using (true);
drop policy if exists device_auth_anon_delete on device_auth;
create policy device_auth_anon_delete on device_auth for delete to anon using (true);
grant insert, select, delete on device_auth to anon;

-- =====================================================================
-- RESET APPENDIX — run ONLY when upgrading a project that still has the OLD
-- integer-id schema (words/texts/tags with bigint `id`/`tag_id`). The desktop
-- app now uses UUID primary keys it generates itself, which a bigint identity
-- column cannot store, so the four synced tables must be dropped and recreated.
-- This DESTROYS all synced rows — the client re-pushes everything on next sync,
-- so the local database is the source of truth. A brand-new project can ignore
-- this. Run these drops, then run the whole script above again:
--
--        drop table if exists word_tags        cascade;
--        drop table if exists tags             cascade;
--        drop table if exists words            cascade;
--        drop table if exists texts            cascade;
--        drop table if exists word_progress     cascade;
--        drop table if exists learning_sessions cascade;
--        drop table if exists quiz_results      cascade;
--        drop table if exists ai_conversations  cascade;
--        drop table if exists word_context      cascade;
--        drop table if exists user_settings     cascade;
--
-- (If this project still has the old invite-only allowlist, also drop it to open
-- registration to everyone:
--        drop trigger if exists enforce_email_allowlist on auth.users;
--        drop function if exists public.enforce_email_allowlist();
--        drop table if exists public.allowed_emails; )
-- =====================================================================
"""


# Personal, single-user schema for the "bring your own Supabase" (advanced) mode.
# Unlike SCHEMA_SQL above, there is NO authentication and NO user_id column: the
# desktop app connects with the project's anon key and reads/writes the tables
# directly. That keeps setup to a single paste-and-run with no SMTP or email
# configuration — but it also means anyone who has this project's URL and anon key can
# read the data, so keep the project private and don't share the key. Primary keys are
# the same client-generated UUIDs, and `deleted_at` mirrors the soft-delete sync, so
# the desktop client talks to either schema unchanged (it upserts on `id` and never
# sends `user_id`). Surfaced via Settings → Sync → "Copy schema SQL".
#
# Row-Level Security is kept ENABLED with a permissive "allow anyone with the anon key"
# policy, rather than turned off. Two reasons: (1) Supabase warns whenever a table
# exposed to the public anon key has RLS off and the dashboard offers a one-click
# "Enable RLS" — clicking it on a policy-less table silently denies EVERYTHING (the
# "42501" insert error), so RLS-off is a trap; (2) RLS-on + a `using (true)` policy is
# functionally the same open access but keeps the linter happy and survives that toggle.
#
# The script is idempotent AND it CONVERTS a project that previously used the multi-user
# SCHEMA_SQL — `create table if not exists` would otherwise skip those existing tables
# and leave their user_id columns + per-user policies in place. So the second half
# unconditionally drops the per-user policies/columns and installs the permissive ones,
# whether the tables are brand-new or carried over.
PERSONAL_SCHEMA_SQL = """\
-- =====================================================================
-- Lingueez personal cloud sync schema (single user, open anon access).
-- For your OWN private Supabase project. Paste into the SQL editor and Run.
-- Works on a fresh project AND converts one that previously used the
-- multi-user schema (it removes user_id and the per-user policies). Safe to re-run.
-- WARNING: anyone with this project's URL + anon key can read this data —
-- keep the project private and do not share the anon key.
-- The apps sync only the four dictionary tables; the learning/stats tables at
-- the end are created for the Lingueez web app (it stores progress there).
-- =====================================================================

-- ---- Tables (created only when this is a fresh project) ---------------
-- Primary keys are UUIDs generated by the desktop client (same value locally and
-- here), so sync is a plain upsert on `id`. `deleted_at` carries the soft-delete.
create table if not exists words (
    id          uuid primary key default gen_random_uuid(),
    row_number  bigint,
    source      text,
    definition  text,
    definition2 text,
    status      text,
    language1   text,
    word1       text,
    language2   text,
    word2       text,
    created_at  timestamptz default now(),
    edited_at   timestamptz,
    deleted_at  timestamptz,
    favorite    boolean default false
);

create table if not exists texts (
    id          uuid primary key default gen_random_uuid(),
    row_number  bigint,
    title       text,
    words       text,
    text        text,
    language    text,
    category    text,
    level       text,
    created_at  timestamptz default now(),
    edited_at   timestamptz,
    deleted_at  timestamptz
);

create table if not exists tags (
    tag_id   uuid primary key default gen_random_uuid(),
    tag_name text not null
);

create table if not exists word_tags (
    word_id uuid not null references words(id) on delete cascade,
    tag_id  uuid not null references tags(tag_id) on delete cascade,
    primary key (word_id, tag_id)
);

-- ---- Make the project personal (also converts an old multi-user one) --
-- Drop the old per-user policies and the user_id columns/constraints, if present.
-- (Policies reference user_id, so they must go before the column.)
drop policy if exists own_rows on words;
drop policy if exists own_rows on texts;
drop policy if exists own_rows on tags;
drop policy if exists own_rows on word_tags;
alter table words     drop constraint if exists words_user_word_key;
alter table tags      drop constraint if exists tags_user_name_key;
alter table words     drop column if exists user_id;
alter table texts     drop column if exists user_id;
alter table tags      drop column if exists user_id;
alter table word_tags drop column if exists user_id;

-- Single-user uniqueness (added only if missing; tolerant of pre-existing
-- duplicate rows so the rest of the script still applies — sync upserts on `id`
-- regardless, so this is only a tidiness guard).
do $$ begin
  begin
    alter table words add constraint words_word_key unique (word1, word2);
  exception when others then null;
  end;
  begin
    alter table tags add constraint tags_name_key unique (tag_name);
  exception when others then null;
  end;
end $$;

-- ---- Open access for the anon key, the safe way ------------------------
-- Keep RLS ENABLED (so Supabase's "enable RLS" nag is already satisfied and can't
-- silently lock you out) but attach a permissive policy that lets the anon key do
-- everything. This is a private single-user project, so open access is intended.
alter table words     enable row level security;
alter table texts     enable row level security;
alter table tags      enable row level security;
alter table word_tags enable row level security;

drop policy if exists allow_all on words;
create policy allow_all on words     for all to anon, authenticated using (true) with check (true);
drop policy if exists allow_all on texts;
create policy allow_all on texts     for all to anon, authenticated using (true) with check (true);
drop policy if exists allow_all on tags;
create policy allow_all on tags      for all to anon, authenticated using (true) with check (true);
drop policy if exists allow_all on word_tags;
create policy allow_all on word_tags for all to anon, authenticated using (true) with check (true);

grant all on table words, texts, tags, word_tags to anon, authenticated;

-- ---- Learning / stats tables (used by the Lingueez WEB app) -----------
-- The desktop and phone apps DON'T use these — they keep learning data on the
-- device. They're included so the Lingueez web app, pointed at this same
-- project, can store sessions, spaced-repetition progress, quiz results, AI
-- tutor chats, per-word AI context and settings. Without them, starting any web
-- activity fails with "Failed to create session". `user_id` holds the web
-- account id (a plain column — a personal project has no auth), and `word_id`
-- references your words so progress is cleaned up when a word is deleted.
create table if not exists word_progress (
    user_id       uuid not null,
    word_id       uuid not null references words(id) on delete cascade,
    last_reviewed timestamptz,
    next_review   timestamptz,
    difficulty    integer default 3,
    review_count  integer default 0,
    correct_count integer default 0,
    ease_factor   real    default 2.5,
    interval_days integer default 1,
    created_at    timestamptz default now(),
    updated_at    timestamptz default now(),
    primary key (user_id, word_id)
);
create index if not exists idx_word_progress_user_next_review on word_progress(user_id, next_review);

create table if not exists learning_sessions (
    id            uuid primary key default gen_random_uuid(),
    user_id       uuid not null,
    session_type  text,
    word_ids      text,
    started_at    timestamptz default now(),
    completed_at  timestamptz,
    words_studied integer default 0,
    words_correct integer default 0
);
create index if not exists idx_learning_sessions_user_started on learning_sessions(user_id, started_at);

create table if not exists quiz_results (
    id             uuid primary key default gen_random_uuid(),
    user_id        uuid not null,
    session_id     uuid references learning_sessions(id) on delete cascade,
    word_id        uuid references words(id) on delete cascade,
    question       text,
    user_answer    integer,
    correct_answer integer,
    is_correct     boolean,
    answered_at    timestamptz default now()
);
create index if not exists idx_quiz_results_session_id on quiz_results(session_id);
create index if not exists idx_quiz_results_user_word on quiz_results(user_id, word_id);

create table if not exists ai_conversations (
    id         uuid primary key default gen_random_uuid(),
    user_id    uuid not null,
    messages   text,
    title      text,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);
create index if not exists idx_ai_conversations_user on ai_conversations(user_id);

create table if not exists word_context (
    user_id           uuid not null,
    word_id           uuid not null references words(id) on delete cascade,
    example_sentences jsonb default '[]',
    collocations      jsonb default '[]',
    usage_patterns    jsonb default '{}',
    synonyms          jsonb default '[]',
    antonyms          jsonb default '[]',
    difficulty_level  text default 'intermediate',
    frequency_rank    integer,
    created_at        timestamptz default now(),
    updated_at        timestamptz default now(),
    primary key (user_id, word_id)
);
create index if not exists idx_word_context_updated on word_context(updated_at);

create table if not exists user_settings (
    user_id                uuid primary key,
    activity_defaults      jsonb default '{}',
    flashcard_show_context boolean default false,
    updated_at             timestamptz default now()
);

-- Open anon access, the safe way (same as the dictionary tables above): keep RLS
-- ENABLED with a permissive policy so Supabase's "enable RLS" nag is satisfied
-- and can't silently lock the tables. Also converts tables previously created
-- RLS-off.
alter table word_progress     enable row level security;
alter table learning_sessions enable row level security;
alter table quiz_results      enable row level security;
alter table ai_conversations  enable row level security;
alter table word_context      enable row level security;
alter table user_settings     enable row level security;

drop policy if exists allow_all on word_progress;
create policy allow_all on word_progress     for all to anon, authenticated using (true) with check (true);
drop policy if exists allow_all on learning_sessions;
create policy allow_all on learning_sessions for all to anon, authenticated using (true) with check (true);
drop policy if exists allow_all on quiz_results;
create policy allow_all on quiz_results      for all to anon, authenticated using (true) with check (true);
drop policy if exists allow_all on ai_conversations;
create policy allow_all on ai_conversations  for all to anon, authenticated using (true) with check (true);
drop policy if exists allow_all on word_context;
create policy allow_all on word_context      for all to anon, authenticated using (true) with check (true);
drop policy if exists allow_all on user_settings;
create policy allow_all on user_settings     for all to anon, authenticated using (true) with check (true);

grant all on table word_progress, learning_sessions, quiz_results, ai_conversations, word_context, user_settings to anon, authenticated;
-- =====================================================================
"""
