# Lingueez — a desktop app for studying vocabulary across languages.
# Copyright (C) 2024-2026 Yurii Lysak
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Additional terms under AGPL-3.0 section 7 apply to this program; see the
# NOTICE file distributed with this source for details.
#
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Postgres DDL for a multi-user Supabase backend (hosted central database).

Only four of the local SQLite tables are mirrored to the cloud — words, texts,
tags, word_tags — with lowercase/snake_case columns (see
``SupabaseClient._map_to_supabase_format``) plus a ``deleted_at`` column the
local tables lack, used for soft-delete sync. Kept as a Python constant rather
than a bundled ``.sql`` resource so it ships intact in the frozen build.

Each row carries a ``user_id`` and Row-Level Security is ON, so every account
sees and touches only its own rows even though the app ships a public anon key —
RLS is what makes that public key safe. Uniqueness is per-user, so two accounts
may hold the same word pair / tag name. Registration is **open** (anyone can sign
up); abuse is held off by email verification + Supabase's built-in rate limits,
not by an allowlist.

Email verification is by **6-digit code**, not a confirmation link, because this
is a desktop app with no web page to land on. Two dashboard settings make that
work (operational, not in this SQL):
  • Authentication → Providers → Email → keep "Confirm email" ON, and configure a
    real SMTP provider (Authentication → Emails) so codes actually deliver.
  • Authentication → Emails → "Confirm signup" template: use the token, e.g.
    ``<p>Your Lingueez code is <b>{{ .Token }}</b></p>`` (the default template
    sends a {{ .ConfirmationURL }} link, which a desktop app can't catch).
"""

# Run this once in the Supabase SQL editor of a fresh, EU-region project (paste,
# then Run). Surfaced verbatim to the user via Settings → Sync ("Copy schema
# SQL"). Keep it in sync with the cloud column names in supabase_client.py and
# the per-user unique constraint upsert_word relies on. The script is idempotent
# (safe to re-run). A MIGRATION appendix at the bottom covers upgrading an older
# pre-accounts project; a brand-new project ignores it.
SCHEMA_SQL = """\
-- =====================================================================
-- Lingueez cloud sync schema (multi-user, Row-Level Security ON).
-- Run once in a fresh EU-region Supabase project's SQL editor.
-- Only these four tables are synced; everything else stays on each device.
-- Safe to re-run (idempotent).
-- =====================================================================

-- ---- Tables -----------------------------------------------------------
create table if not exists words (
    id          bigint primary key generated by default as identity,
    user_id     uuid not null default auth.uid() references auth.users(id) on delete cascade,
    row_number  bigint,
    source      text,
    definition  text,
    definition2 text,
    status      text,
    language1   text,
    word1       text,
    language2   text,
    word2       text,
    created_at  timestamptz default now(),
    edited_at   timestamptz,
    deleted_at  timestamptz,
    favorite    boolean default false,
    constraint words_user_word_key unique (user_id, word1, word2)
);

create table if not exists texts (
    id          bigint primary key generated by default as identity,
    user_id     uuid not null default auth.uid() references auth.users(id) on delete cascade,
    row_number  bigint,
    title       text,
    words       text,
    text        text,
    language    text,
    category    text,
    level       text,
    created_at  timestamptz default now(),
    edited_at   timestamptz,
    deleted_at  timestamptz
);

create table if not exists tags (
    tag_id   bigint primary key generated by default as identity,
    user_id  uuid not null default auth.uid() references auth.users(id) on delete cascade,
    tag_name text not null,
    constraint tags_user_name_key unique (user_id, tag_name)
);

create table if not exists word_tags (
    word_id bigint not null references words(id) on delete cascade,
    tag_id  bigint not null references tags(tag_id) on delete cascade,
    user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
    primary key (word_id, tag_id)
);

-- ---- Row-Level Security: each user sees only their own rows ------------
alter table words     enable row level security;
alter table texts     enable row level security;
alter table tags      enable row level security;
alter table word_tags enable row level security;

drop policy if exists own_rows on words;
create policy own_rows on words     for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists own_rows on texts;
create policy own_rows on texts     for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists own_rows on tags;
create policy own_rows on tags      for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists own_rows on word_tags;
create policy own_rows on word_tags for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---- Open registration --------------------------------------------------
-- Anyone may sign up; there is no invite allowlist. New accounts are verified by
-- a 6-digit email code (configure SMTP + the "Confirm signup" email template to
-- use {{ .Token }} — see the module docstring). If this project was created with
-- the old invite-only trigger, the migration appendix below removes it.

-- ---- GDPR: let a signed-in user delete their own account + all data ----
-- A client with the anon key cannot delete an auth.users row directly, so this
-- SECURITY DEFINER function does it on the user's behalf. The on-delete-cascade
-- foreign keys above then wipe every one of their rows atomically. No
-- service-role key is ever needed (or shipped) for this.
create or replace function public.delete_account()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from auth.users where id = auth.uid();
end;
$$;

revoke all on function public.delete_account() from public, anon;
grant execute on function public.delete_account() to authenticated;

-- =====================================================================
-- MIGRATION APPENDIX — run ONLY if upgrading a project created before
-- accounts existed (it already has words/texts/tags without a user_id).
-- A brand-new project can ignore everything below.
--
--   1. Add the column (nullable for now):
--        alter table words     add column if not exists user_id uuid;
--        alter table texts     add column if not exists user_id uuid;
--        alter table tags      add column if not exists user_id uuid;
--        alter table word_tags add column if not exists user_id uuid;
--        alter table texts     add column if not exists deleted_at timestamptz;
--
--   2. Backfill existing rows to YOUR account id (sign up first, then copy
--      your id from Authentication -> Users):
--        update words     set user_id = '<YOUR-AUTH-UID>' where user_id is null;
--        update texts     set user_id = '<YOUR-AUTH-UID>' where user_id is null;
--        update tags      set user_id = '<YOUR-AUTH-UID>' where user_id is null;
--        update word_tags set user_id = '<YOUR-AUTH-UID>' where user_id is null;
--
--   3. Enforce ownership + per-user uniqueness, then re-run this whole script:
--        alter table words drop constraint if exists words_word1_word2_key;
--        alter table tags  drop constraint if exists tags_tag_name_key;
--        alter table words     alter column user_id set not null;
--        alter table texts     alter column user_id set not null;
--        alter table tags      alter column user_id set not null;
--        alter table word_tags alter column user_id set not null;
--
--   4. If this project still has the old invite-only allowlist, drop it to open
--      registration to everyone:
--        drop trigger if exists enforce_email_allowlist on auth.users;
--        drop function if exists public.enforce_email_allowlist();
--        drop table if exists public.allowed_emails;
-- =====================================================================
"""
